### ISSUE TITLE
Splitting work

### ISSUE THREAD

**Issue by VictorGa** [MostlyAdequate/mostly-adequate-guide-es#1]
@guumaster @EdgarOrtegaRamirez how are we splitting work?

I propose each one pick one chapter/part and later we revise them all together.
What do you think guys?

**Comment by EdgarOrtegaRamirez** [comment]
@VictorGa splitting sounds great, would you mind taking the lead?

**Comment by VictorGa** [comment]
Ok, I will start with the main Readme and first chapter. 

@guumaster and @EdgarOrtegaRamirez agree?

**Comment by guumaster** [comment]
Ok, I'll get chapter 3 on Pure functions.

**Comment by guumaster** [comment]
Remember to create new files for each chapter translations. 

Also, we all have permission to directly push commits, but we should go with branches and PR.

**Comment by EdgarOrtegaRamirez** [comment]
I'll go for chapter 3 (#2 updated)

**Comment by guumaster** [comment]
Also, I think we should not translate the examples or any variable name. Thoughts?

**Comment by VictorGa** [comment]
I think comments maybe is good but variables I'm not that sure. I think the majority of programmers are used to read code in english, maybe translating variables/code makes it less readable. 

I've checked the other translations and no one has the code translated, just comments for example french version.

What do you think?

**Comment by EdgarOrtegaRamirez** [comment]
I agree with you guys.

**Comment by guumaster** [comment]
:+1: ok, comments but not code.

**Comment by VictorGa** [comment]
:+1: 

I have first draft for Readme translated it. Are we forking it or working in branches?

**Comment by guumaster** [comment]
Just branch/PR

**Comment by VictorGa** [comment]
@guumaster, @EdgarOrtegaRamirez I will take chapter 5 now.

**Comment by guumaster** [comment]
ok, i'll close this one and we can keep track on the other issue #2
