### ISSUE TITLE
Help :(

### ISSUE THREAD

**Issue by EdgarOrtegaRamirez** [MostlyAdequate/mostly-adequate-guide-es#10]
In the following context:
`It's like donning your heaviest parka in the dead of July just to blast the air and demand an ice lolly.`

What's the meaning of `dead of July`and `blast the air`?

I've translated it to `Es como ponerte tu parka más pesada al final de julio sólo para arruinar el aire y exigir una paleta`, but I'm not totally sure about it.

**Comment by VictorGa** [comment]
Creo que es quiere decir lo siguiente: __es como si te vistieses con tu parka más pesada a finales de un julio mortal pretendiendo aliviar el calor y pides un helado__

Crees que tiene sentido?

Muchas expresiones tienen que ser re-escritas casi en su totalidad para que tengan sentido en español.

**Comment by EdgarOrtegaRamirez** [comment]
@VictorGa gracias! Tiene mejor sentido, actualizaré el PR del capítulo 2.

**Comment by guumaster** [comment]
Ademas tiene bastante lenguaje coloquial americano. Es buena idea tener hilos como este para aclararlos y buscar una frase similar que mantenga el sentido. 

Ya que esta aclarado. cierro.
