### ISSUE TITLE
Traducción del capitulo 8 (acerca de los functores)

### ISSUE THREAD

**Issue by idcmardelplata** [MostlyAdequate/mostly-adequate-guide-es#19]
Hola, acabo de terminar de traducir el capitulo 8 (obviamente muy sujeto a revisión), [aca puede leerse](https://github.com/idcmardelplata/mostly-adequate-guide-es/blob/ch-8-devel/ch8-es.md), quisiera saber si se continua con el proyecto de traducción del libro o si esta abandonado, puesto que no veo commits nuevos desde hace tiempo, desde ya un saludo a todos y gracias por las traducciones.

**Comment by guumaster** [comment]
Esta un poco dejada, pero podríamos retomarla. Haz un PR así es mas fácil revisar las diferencias.

**Comment by idcmardelplata** [comment]
disculpame que sea tan bruto, que es un pr?

**Comment by guumaster** [comment]
Perdona, un Pull Request, para hacer merge entre tu repo clonado y el mio. Así puedo ver el texto original y la traducción, y sobre esa petición, se puede hacer comentarios y revisiones antes de juntar las versiones.

**Comment by idcmardelplata** [comment]
Ya esta guumaster, disculpa la demora pero todavía no me amigue con github xd.
