### ISSUE TITLE
Nuevos capítulos Merger

### ISSUE THREAD

**Issue by ferborva** [MostlyAdequate/mostly-adequate-guide-es#22]
Buenas! Dados los ultimos avances en el libro por parte de los creadores, ¿hay planes de traer lo nuevo a este repo? Me veo con algo de tiempo entre manos y me gustaria aportar en la traducción y actualización del libro

**Comment by EstebanMarin** [comment]
Todos los aportes son bienvenidos. En el readme hay instrucciones de como hacer un PR
