### ISSUE TITLE
Translation notes

### ISSUE THREAD

**Issue by guumaster** [MostlyAdequate/mostly-adequate-guide-es#3]
Here we can discuss about very common terms, hard to translate or un-translatable ones. 
## Common terms
- returns: _devuelve_
- memoization: _memoización_
- signature: _firma_
- reuse: _reutilizar_
- to mock: _mockear_ (used as a verb, not a propper translation, but the accepted programming term)
## Hard to tranlate
- cacheable: _almacenable en cache_ 
- cached: _en cache/tener en cache_ 
## Untranslatable

These terms refers to a Math concept or a singular name.
## Free translations
-  the cat's evening wear: _la guinda del pastel_
  - Curry/Currying: I prefer to keep this name _as is_ because it is a reference to a personal name and I've never seen it translated before. 
  - Monads. A math terms better kept _as is_ 
  - functors: same as _monads_ 
  - closure: It could be translated as `cerradura` but it's awful and nobody uses it.
  - bug: this terms is broadly use in different languages. I think we should keep it as it is.
## Programming terms

These terms may have translations, but they are not commonly translated in programming context.
- Socket / Web Socket
- Web Worker

**Comment by EdgarOrtegaRamirez** [comment]
Is `callable` an untranslatable term?

**Comment by EdgarOrtegaRamirez** [comment]
`store` = `almacenar`?

**Comment by VictorGa** [comment]
I  wouldn't translate those two concepts. @guumaster what you think?
