### ISSUE TITLE
Traducción del título

### ISSUE THREAD

**Issue by ferllop** [MostlyAdequate/mostly-adequate-guide-es#44]
Dado que las traducciones de los libros incluyen el título, aquí dejo mis propuestas:

1. La Guía del Profesor Frisby en Gran Parte Adecuada para la Programación Funcional
2. La Guía del Profesor Frisby en su Mayor Parte Adecuada para la Programación Funcional
3. La Guía del Profesor Frisby Mayormente Adecuada para la Programación Funcional
4. La Guía Más Adecuada del Profesor Frisby para la Programación Funcional

Mi voto va para la 2, ¡o para otra nueva propuestas que surjan!

La 1 es muy parecida a la 2, pero me suena peor (menos adecuada XD)
La 3 me suena demasiado coloquial, aunque también válida y podría ir con el estilo de escritura del autor.
La 4.. es la  opción que da deepl... no se, demasiado prepotente. No se si eso es lo que quiere transmitir el autor.

**Comment by EstebanMarin** [comment]
Me gusta también la 2da propuesta!

**Comment by ferllop** [comment]
Llevado a cabo en [pull request 45](https://github.com/MostlyAdequate/mostly-adequate-guide-es/pull/45)
