### ISSUE TITLE
Chapter 2: [^coach?]

### ISSUE THREAD

**Issue by EdgarOrtegaRamirez** [MostlyAdequate/mostly-adequate-guide-es#7]
Do you guys know what does `[^coach?]` mean?

**Comment by guumaster** [comment]
Not sure. We may mention @DrBoolean to clarify meaning?

The full phrase is `When we say functions are "first class", we mean they are just like everyone else... so normal class[^coach?]` What does `coach` mean on that context?

**Comment by DrBoolean** [comment]
On flights you can sit in "first class", "business class", or "coach". It's a little joke since most people fly coach.

**Comment by guumaster** [comment]
Thanks! Its true, its funny to refers this things as "first class".
