### ISSUE TITLE
Doubts about translating some terms

### ISSUE THREAD

**Issue by VictorGa** [MostlyAdequate/mostly-adequate-guide-es#8]
@guumaster and @EdgarOrtegaRamirez let's place here doubts about translating some terms.

@EdgarOrtegaRamirez could you move your two questions from #3  here?

**Comment by EdgarOrtegaRamirez** [comment]
1. Should we translate `to store` as `almacenar`?
2. Is `callable` an untranslatable term?

**Comment by guumaster** [comment]
1. `almacenar` seems ok.
 
2. `callable` is a hard one, `invocable`?

We should point out terms in context to get a better picture.

**Comment by VictorGa** [comment]
Como traducimos `Functional husbandry`?  `Cultivo funcional`?

**Comment by EdgarOrtegaRamirez** [comment]
Qué piensas de `Cultivo de funciones`?

**Comment by EdgarOrtegaRamirez** [comment]
@VictorGa `Cultivo funcional ` me parece la mejor traducción.

**Comment by guumaster** [comment]
Aquí cultivo se usa mas en el sentido de criar que de cultivar, osea como si fueran animales en lugar de vegetales. Tiene ese juego de palabras porque habla que componer funciones da lugar a nuevas funciones, como un criadero de funciones. Tal vez le podría ir bien la traducción `criadero funcional` o `reproducción funcional`.

**Comment by VictorGa** [comment]
@guumaster creo que reproducción funcional va más en la línea de lo que el quiere decir.

Gracias @EdgarOrtegaRamirez y @guumaster

**Comment by EdgarOrtegaRamirez** [comment]
Están de acuerdo en traducir **loop** como **ciclo**?

**Comment by VictorGa** [comment]
Creo que es mejor **bucle**, ya que **ciclo** se refiere a **cycle**.

Estáis de acuerdo?

**Comment by EdgarOrtegaRamirez** [comment]
@VictorGa no problem, thanks.

**Comment by EdgarOrtegaRamirez** [comment]
Guys what about **namespace**? Is it an untranslatable term? or can I use **espacio de nombres**?

**Comment by guumaster** [comment]
I prefer namespace. But am fine with both

**Comment by VictorGa** [comment]
:+1: with namespace

**Comment by EdgarOrtegaRamirez** [comment]
Can we translate **Variadic** as **Variadica**?

**Comment by guumaster** [comment]
Hmmm parece un falso amigo. Yo lo dejaba como estaba
